name: Delete Workflow on PR Close
on:
  pull_request:
    types: [closed]

jobs:
  DeleteVersionAfterPRClosed:
    runs-on: ubuntu-latest
    env:
      BUILD_TAG: pr-${{ github.event.number }}
      APP_NAME: pipeline-test-app
    steps:
      - name: Authenticate to Google App Engine
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GAE_SERVICE_ACCOUNT_CREDENTIALS }}
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0

      - name: Delete Version
        run: |
          gcloud app versions delete ${{ env.BUILD_TAG }}