name: Deploy App to Google App Engine
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy Production Code to Google App Engine
    runs-on: ubuntu-18.04
    permissions:
      contents: read
      id-token: write
    env:
      BUILD_TAG: pr-${{ github.sha }}
      APP_NAME: pipeline-test-app
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Authenticate to Google App Engine
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GAE_SERVICE_ACCOUNT_CREDENTIALS }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0

    - name: Deploy
      uses: google-github-actions/deploy-appengine@v0.5.0
      with:
        version: ${{ env.BUILD_TAG }}
        promote: false