name: Create preview environment on PR
on:
  pull_request:
    types: [opened,edited,reopened,synchronize]
jobs:
  build:
    name: Test and Deploy PR to GAE version
    runs-on: ubuntu-18.04
    permissions:
      contents: read
      id-token: write
    env:
      BUILD_TAG: pr-${{ github.event.number }}
      APP_NAME: pipeline-test-app
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install npm Libraries
      run: |
        npm install

    - name: Run Pre-deploy Tests
      run: |
        npm test

    - name: Authenticate to Google App Engine
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GAE_SERVICE_ACCOUNT_CREDENTIALS }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0

    - name: Deploy
      uses: google-github-actions/deploy-appengine@v0.5.0
      with:
        version: ${{ env.BUILD_TAG }}
        promote: false